### ISSUE TITLE
FEAT: Host Backend Java Server on GCP

### ISSUE THREAD

**Issue by cynical-cheddar** [Free-Pizza-Team-QA-LBG/QA-Backend#1]

**Comment by BenSnellgrove** [comment]
Has dockerfile, should be ready for host w/ Jenkins and associated mcguffins

**Comment by BenSnellgrove** [comment]
![Image](https://github.com/user-attachments/assets/43b33c9f-0b8b-4e62-92ef-f9a9f3c44905)
Done.
