### ISSUE TITLE
EPIC: Set up and interface with db using Java framework such as SpringBoot

### ISSUE THREAD

**Issue by cynical-cheddar** [Free-Pizza-Team-QA-LBG/QA-Backend#2]

**Comment by BenSnellgrove** [comment]
![Image](https://github.com/user-attachments/assets/b2a9d1cd-62f5-49e9-86ad-d69c552bd16e)

**Comment by BenSnellgrove** [comment]
![Image](https://github.com/user-attachments/assets/50337ed1-eced-48ec-bc4b-81f444f79d01)
Heartbeat ping, returning 200 and a light-hearted confirmation

**Comment by BenSnellgrove** [comment]
Marking as done, backend just needs to be hosted
